// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPNIwglBtioKyH5-iV5-jiQ0Stv9-qKYw',
    appId: '1:296761899748:web:0a87693d87d7b9c0754af1',
    messagingSenderId: '296761899748',
    projectId: 'fast-pizza-e5f98',
    authDomain: 'fast-pizza-e5f98.firebaseapp.com',
    storageBucket: 'fast-pizza-e5f98.firebasestorage.app',
    measurementId: 'G-WBF25JKS75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnQd8FwGykRkDDAOrSvYMY_A2vrtGo1so',
    appId: '1:296761899748:android:f683cd9f47363481754af1',
    messagingSenderId: '296761899748',
    projectId: 'fast-pizza-e5f98',
    storageBucket: 'fast-pizza-e5f98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHchy4dtN_E4IGNbc4PiivVeAALCpZE-4',
    appId: '1:296761899748:ios:121b1ecc2833ad88754af1',
    messagingSenderId: '296761899748',
    projectId: 'fast-pizza-e5f98',
    storageBucket: 'fast-pizza-e5f98.firebasestorage.app',
    iosBundleId: 'com.example.decisionJarProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHchy4dtN_E4IGNbc4PiivVeAALCpZE-4',
    appId: '1:296761899748:ios:121b1ecc2833ad88754af1',
    messagingSenderId: '296761899748',
    projectId: 'fast-pizza-e5f98',
    storageBucket: 'fast-pizza-e5f98.firebasestorage.app',
    iosBundleId: 'com.example.decisionJarProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPNIwglBtioKyH5-iV5-jiQ0Stv9-qKYw',
    appId: '1:296761899748:web:a29afa58b94e14e1754af1',
    messagingSenderId: '296761899748',
    projectId: 'fast-pizza-e5f98',
    authDomain: 'fast-pizza-e5f98.firebaseapp.com',
    storageBucket: 'fast-pizza-e5f98.firebasestorage.app',
    measurementId: 'G-GJJ6VG4913',
  );
}
